# Generated by Django 2.2.5 on 2020-11-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to='img/upload/<django.db.models.query_utils.DeferredAttribute object at 0x000002680AA0E5F8>'),
        ),
    ]
